### ISSUE TITLE
Collision is not fully fixed graphically

### ISSUE THREAD

**Issue by Anonymous941** [Herringway/earthbound#123] opened 2023-05-22 14:30 UTC
The recent fix for collision doesn't work for the top right corner of the trees for some reason, so the party appears on top of some parts of the tree

**Comment by Herringway** [comment] 2023-05-22 15:33
That relies on entity tile collision, which is separate code from the leader tile collision. Likely related to #124.

**Comment by Herringway** [comment] 2023-05-23 01:10
Dupe of #66

**Closed by Herringway** 2023-05-23 01:10 UTC
