### ISSUE TITLE
Game crashes on Onett hill top

### ISSUE THREAD

**Issue by Anonymous941** [Herringway/earthbound#84] opened 2023-04-19 17:47 UTC
I've been trying to compile this on Linux, and am getting a lot of problems.  The game works fine until I go to the top of the Onett hill where I'm supposed to meet Porky.  Then, NPCs disappear and randomly reappear and eventually I get an assertion error:

```plain
2023-04-19T13:44:20.325 [info] rendering.d:143:loadRenderer SnesDrawFrame initialized
2023-04-19T13:44:20.386 [info] rendering.d:148:loadRenderer SDL video subsystem initialized (x11)
2023-04-19T13:44:20.416 [info] rendering.d:192:initializeRenderer SDL renderer subsystem initialized (opengl)
2023-04-19T13:44:20.444 [info] main.d:105:main SDL audio subsystem initialized (pulseaudio)
2023-04-19T13:44:20.478 [info] gamepad.d:26:initializeGamepad SDL game controller subsystem initialized
2023-04-19T13:44:20.881 [info] main.d:137:main Text files newer than cache, rebuilding...
2023-04-19T13:44:27.506 [info] audio.d:39:doMusicEffect Music effects not yet implemented
2023-04-19T13:44:31.921 [info] audio.d:39:doMusicEffect Music effects not yet implemented
2023-04-19T13:44:31.921 [info] audio.d:39:doMusicEffect Music effects not yet implemented
2023-04-19T13:44:33.941 [info] audio.d:39:doMusicEffect Music effects not yet implemented
2023-04-19T13:44:34.457 [info] audio.d:39:doMusicEffect Music effects not yet implemented
2023-04-19T13:44:35.974 [info] audio.d:35:setAudioChannels Setting audio channels not yet implemented
2023-04-19T13:44:35.990 [info] audio.d:39:doMusicEffect Music effects not yet implemented
2023-04-19T13:44:35.990 [info] audio.d:39:doMusicEffect Music effects not yet implemented
2023-04-19T13:45:02.889 [info] audio.d:39:doMusicEffect Music effects not yet implemented
2023-04-19T13:45:02.890 [info] audio.d:39:doMusicEffect Music effects not yet implemented
2023-04-19T13:45:02.890 [info] audio.d:39:doMusicEffect Music effects not yet implemented
core.exception.AssertError@source/earthbound/bank00.d(941): Assertion failure
----------------
??:? _d_assertp [0x55b81ac194a0]
source/earthbound/bank00.d:941 short earthbound.bank00.createEntity(short, short, short, short, short) [0x55b81aac2a92]
source/earthbound/bank00.d:1107 void earthbound.bank00.trySpawnNPCs(short, short) [0x55b81ab1861a]
source/earthbound/bank00.d:1166 void earthbound.bank00.spawnNPCsColumn(short, short) [0x55b81ab18836]
source/earthbound/bank00.d:666 void earthbound.bank00.refreshMapAtPosition(short, short) [0x55b81ab1734b]
source/earthbound/bank00.d:1950 void earthbound.bank00.centerScreen(short, short) [0x55b81aac4e4a]
source/earthbound/bank00.d:2460 void earthbound.bank00.unknownC04C45() [0x55b81aac50fb]
source/earthbound/bank00.d:2680 void earthbound.bank00.unknownC05200() [0x55b81aa8478c]
source/earthbound/bank00.d:6372 void earthbound.bank00.jumpToLoadedMovementPtr() [0x55b81aa86eed]
source/earthbound/bank00.d:5411 void earthbound.bank00.unknownC094D0(short, short) [0x55b81aa86b02]
source/earthbound/bank00.d:5374 void earthbound.bank00.runActionscriptFrame() [0x55b81aa86779]
source/earthbound/bank00.d:8114 void earthbound.bank00.ebMain() [0x55b81aa8b598]
source/earthbound/bank00.d:8214 void earthbound.bank00.gameInit() [0x55b81a9e4536]
source/earthbound/bank00.d:4395 void earthbound.bank00.start() [0x55b81a9ddd54]
??:? void core.thread.context.Callable.opCall() [0x55b81ac240c6]
??:? fiber_entryPoint [0x55b81ac72a43]
```

**Comment by charasyn** [comment] 2023-04-19 18:49
I think this is a dupe of #47

**Closed** 2023-04-19 20:03 UTC
Labels: duplicate
